In [1]:
from stl import mesh
import numpy as np

In [2]:
your_mesh = mesh.Mesh.from_file('brain.stl')

In [3]:
volume, cog, inertia = your_mesh.get_mass_properties()
print("Volume = {0}".format(volume)) 
print("Position of the center of gravity (COG) = {0}".format(cog)) 
print("Inertia matrix at expressed at the COG = {0}".format(inertia[0,:])) 
print(" {0}".format(inertia[1,:])) 
print(" {0}".format(inertia[2,:]))

Volume = 604408.5443936392
Position of the center of gravity (COG) = [ -1.0908088  -98.39870079  59.2050641 ]
Inertia matrix at expressed at the COG = [ 8.00925941e+08 -1.69293234e+07  5.16299525e+06]
 [-1.69293234e+07  6.03594289e+08 -5.28142912e+07]
 [ 5.16299525e+06 -5.28142912e+07  1.02113920e+09]


In [4]:
# def calc_COG(v1,v2,weight1,weight2):
#   total_w = weight1 + weight2
#   w1_frac = weight1/total_w
#   w2_frac = weight2/total_w
#   COG = w1_frac*v1 + w2_frac*v2
#   return COG

def calc_COG(vectors,weights):
  total_w = np.sum(weights)
  fracs = weights/total_w
  COG = np.sum(np.array([fracs[i]*vectors[i] for i in range(len(vectors))]), axis = 0)
  return COG

In [5]:
#setup input
cutout = np.array([-3.27922964, -103.48350591,   32.27894635]) # 601786.8577301032
skull = np.array([-1.51645437, -82.60931843,  25.82963429])
brain = np.array([-1.0908088,  -98.39870079,  59.2050641])
COG_nose = np.array([0,-10,-8])
COG_neck = np.array([0,-35,-70])


silic_brain_gcc = 1.07
silic_CSF_gcc = 1.18

w_cutout = 601.7868590215809 * silic_CSF_gcc
w_skull = 345
w_brain = 604.4085443936392 * silic_brain_gcc
w_nose = 8 * 8.6
w_neck = 38* 8.46


In [6]:
#compute center of gravity
skull_nose_cog = calc_COG(np.array([skull,COG_neck]), np.array([w_skull,w_neck]))
print(skull_nose_cog)
print("Total weight: ", w_cutout+w_skull+w_brain)

[ -0.78498493 -59.64472281 -20.39427465]
Total weight:  1701.8256361466592


In [7]:
# Calculate location for cylinder
w_skull_nose = w_skull + w_nose

end_cog = np.array([0,-55,-20])
dir_vec = end_cog - skull_nose_cog


b = (18*8.6)
s = (b*end_cog + end_cog*(w_skull_nose) - w_skull*skull - w_nose*COG_nose)/(b*(dir_vec/np.linalg.norm(dir_vec)))

print(s)

[   20.35201217   -13.70634737 -1528.3070407 ]


In [8]:
x = 202
z = 119.3

att_x =10 
att_z = -100
print("x-dist: ", x-att_x)
print("z-dist: ",z-att_z+15)

x-dist:  192
z-dist:  234.3
